---
abstract: "Manipulates the Macintosh Finder's .DS_Store files."
author:
  - 'Wim Lewis <wiml@hhhh.org>'
build_requires:
  Test::More: 0.61
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mac-Finder-DSStore
provides:
  Mac::Finder::DSStore:
    file: DSStore.pm
    version: 0.95
  Mac::Finder::DSStore::BuddyAllocator:
    file: BuddyAllocator.pm
    version: 0.95
  Mac::Finder::DSStore::BuddyAllocator::Block:
    file: BuddyAllocator.pm
  Mac::Finder::DSStore::BuddyAllocator::StringBlock:
    file: BuddyAllocator.pm
  Mac::Finder::DSStore::BuddyAllocator::WriteBlock:
    file: BuddyAllocator.pm
  Mac::Finder::DSStore::Entry:
    file: DSStore.pm
recommends:
  Mac::Files: 0
  Mac::Memory: 0
requires:
  Encode: 1.20
  perl: v5.6.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.95
